image:
  file: .gitpod.Dockerfile
tasks:
  - name: Redis Server Setup
    init: echo 'REDIS SERVER STARTING'
    command: redis-server --daemonize yes
  - name: Npm Install
    init: |
      cd src
      npm install
  - name: Hidden Environment File Setup
    init: |
      cd src
      echo "DISCORD_TOKEN=$DISCORD_TOKEN" > .env
      echo "CLIENT_ID"=$CLIENT_ID >> .env
vscode:
  extensions:
    - eamodio.gitlens
    - GitHub.copilot
    - joshbolduc.commitlint
