version: '3.8'

networks:
  listing-network:
    driver: bridge

volumes:
  redis-data:  # Define the volume named redis-data

services:
  endless-0:
    container_name: endless-herald
    image: endless-reminder
    env_file:
      - .env
    volumes:
      - ./logs:/src/app/logs
    restart: unless-stopped
    networks:
      - listing-network
    depends_on:
      - redis-0

  redis-0:
    image: redis
    container_name: endless-redis
    volumes:
      - ./redis-data:/data  # Mount the volume at /data inside the container
    ports:
      - "6380:6379"
    command: redis-server --save 300 1
    networks:
      - listing-network
    restart: unless-stopped


