version: '3.8'
services:
  bot:
    build: .
    env_file:
      - .env
    depends_on:
      - redis
    networks:
      - listing-network
    volumes:
      - ./logs:/usr/src/app/logs

  redis:
    image: redis
    ports:
      - "6379:6379"
    networks:
      - listing-network

networks:
  listing-network:
    driver: bridge
