version: '3.8'

networks:
  listing-network:
    driver: bridge

services:
  endless-0:
    container_name: endless-herald
    build:
      context: .
    env_file:
      - .env
    volumes:
      - ./logs:/src/app/logs
    restart: unless-stopped
    networks:
      - listing-network
    depends_on:
      - redis

  redis:
    image: redis
    container_name: endless-redis
    ports:
      - "6380:6379"
    networks:
      - listing-network
    restart: unless-stopped


